version: '3.9'
services:
  database:
    image: 'postgres:alpine'
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_PASSWORD=egorka02+
    ports:
     - '5432:5432'
    networks:
      - backend
  spring-boot-app:
    image: 'vasilenka/psychologist_appointment-backend:latest'
    ports:
      - '8080:8080'
    depends_on:
      - database
    environment:
      - spring.datasource.url=jdbc:postgresql://database/postgres
    networks:
      - backend
  pgAdmin:
    image: dpage/pgadmin4
    depends_on:
      - database
    environment:
      - PGADMIN_DEFAULT_EMAIL=root@root.com
      - PGADMIN_DEFAULT_PASSWORD=egorka02+
    ports:
      - '5050:80'
    networks:
      - backend
networks:
  backend: